//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace versenyzok.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("versenyzok.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to név;születési_dátum;nemzetiség;rajtszám
        ///Lewis Hamilton;1985.01.07;brit;44
        ///Nick Heidfeld;1977.05.10;német;
        ///Nico Rosberg;1985.06.27;német;6
        ///Fernando Alonso;1981.07.29;spanyol;14
        ///Heikki Kovalainen;1981.10.19;finn;
        ///Kazuki Nakajima;1985.01.11;japán;
        ///Sébastien Bourdais;1979.02.28;francia;
        ///Kimi Räikkönen;1979.10.17;finn;7
        ///Robert Kubica;1984.12.07;lengyel;88
        ///Timo Glock;1982.03.18;német;
        ///Takuma Sato;1977.01.28;japán;
        ///Nelson Piquet Jr;1985.07.25;brazíl;
        ///Felipe Massa;1981.04.25;brazíl;19
        ///David Coulthard; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pilotak {
            get {
                return ResourceManager.GetString("pilotak", resourceCulture);
            }
        }
    }
}
